### ISSUE TITLE
Error with mlio.SageMakerPipe that seems CSV-column header related?

### ISSUE THREAD

**Issue by la-cruche** [awslabs/ml-io#19]
I have using mlio.SageMakerPipe to stream records in a SageMaker pipe-mode training container (sklearn 0.23-1 framework container on a C5). The input consists of 24x 800Mb csv files with their headers.

I use this snippet of code:

```
pipe = mlio.SageMakerPipe('/opt/ml/input/data/train')
reader_params = mlio.DataReaderParams(dataset=[pipe], batch_size=args.batch)
batches = mlio.CsvReader(reader_params)
   
for epoch in range(args.epochs):

  for batch in batches:  # CsvReader is simply an iterator over mini-batches of data.
     df = to_pandas(batch)  # Convert the mini-batch into a pandas DataFrame
     print(df.shape)
     print(df.columns.tolist())
     print(df.head())
     ...incremental model training code here...
```

and I see in my prints the shape, columns and head of dataframes correctly displayed.
However, after several (hundreds? thousands?) of such print statements I have the following error:
`mlio.InvalidInstanceError: The column 'duration' of the row #9,710,124 in the data store '/opt/ml/input/data/train' cannot be parsed as float64. Its string value is 'duration'.`

`duration` being a column in my csv and the dataframes.

What could cause this?

**Comment by cbalioglu** [comment]
This is one of the shortcomings of pipe mode and is not specific to MLIO. As we have no way to determine where a file ends and a new one starts while reading an opaque byte stream from a pipe, we consider everything after the header of the first file as regular data rows. You have four options to solve the issue:

1) Use pipe mode, but make sure that only the first CSV file (the one when files are sorted in alphabetical order) has a header.
2) Use pipe mode, but make sure that no files have a header, and explicitly specify the columns via MLIO.
3) Use file mode
4) Use MLIO's `S3Object` to read directly from S3 bypassing SageMaker's data agent.

**Comment by la-cruche** [comment]
thanks!
