### ISSUE TITLE
How to install locally?

### ISSUE THREAD

**Issue by icdishb** [awslabs/ml-io#5]
Hello.

I am planning to use this package locally. Is there a installation instruction?

Thanks,
Huibin

**Comment by laurencer** [comment]
I actually have some instructions that work but I'll leave it for @cbalioglu to add something similar to the README (and make sure I've got the process right).

1. Basically you need to install: `cmake`, `automake`, `ninja`, and `libtool` (you can do so via brew if you are on Mac - `brew install cmake automake ninja libtool`).

2. Then make a dependencies directory somewhere on your filesystem (it doesn't have to be in the source root but can be): `export MLIO_DEPS=./mlio-deps``mkdir ${MLIO_DEPS}`. Use the `./build-tools/build-dependency ${MLIO_DEPS}/ all` to download and install all the library dependencies.

3. Make a directory to hold the CMake build - `export MLIO_CMAKE_DIR=cmake_build; mkdir ${MLIO_CMAKE_DIR}; cd ${MLIO_CMAKE_DIR}`.

4. Either use `ccmake ..` to configure the build or use a build string like: `cmake -DPYTHON_EXECUTABLE=$(which python3.7) -DCMAKE_BUILD_TYPE=Debug -DCMAKE_FIND_ROOT_PATH=${MLIO_DEPS} -DMLIO_INCLUDE_LIB=TRUE -DMLIO_INCLUDE_PYTHON_EXTENSION=TRUE -DMLIO_INCLUDE_ARROW_INTEGRATION=OFF ../`.

5. Do a build `cmake --build . -- -j $(sysctl -n hw.ncpu)`

6. (optionally; only need to do this once) if you want to use it from Python; make sure you have Conda installed. Activate your mlio conda environment (`conda activate mlio-dev`). Navigate to the `mlio-py` directory (`cd ../src/mlio-py`) and install using pip in dev mode (`pip install -e .`). Now you can use it in Python and it will update automatically when you rebuild (you do need to restart Python though).

There are a couple of gotchas you can run into. E.g. if you do `cmake` in a conda environment it can sometimes pick up the wrong version of Protobufs. Similarly if you do `cmake` outside of a conda environment sometimes it can pick up the wrong version of Python.

**Comment by cbalioglu** [comment]
I am working on the documentation and plan to have the first draft finished soon (most likely in about a week) In the meantime if you just want to use the package without building it locally, you can use simply Conda. In a Conda environment run the following command line:

```
conda install -c mlio -c conda-forge mlio-py
```

This will use the conda-forge and mlio channels for resolving packages. `mlio-py` is the name of our Python package.

**Comment by aws-patlin** [comment]
Build documentation is available at https://github.com/awslabs/ml-io/blob/master/doc/build.md
